In [3]:
import pandas as pd

data = pd.read_csv('finance_customer.csv')

data.head()

,customer_id,emp_title,emp_length,home_ownership,annual_inc,annual_inc_joint,verification_status,zip_code,addr_state,avg_cur_bal,Tot_cur_bal
0,customer 1,NaN,none,Rent,25000.0,none,Verified,010xx,MA,6864,34322
1,customer 2,NaN,none,Mortgage,185000.0,none,Not Verified,010xx,MA,7930,150674
2,customer 3,NaN,none,Mortgage,120000.0,none,Source Verified,015xx,MA,15652,281735
3,customer 4,NaN,none,Mortgage,75000.0,120000,Verified,077xx,NJ,14042,379132
4,customer 5,NaN,none,Mortgage,36000.0,none,Source Verified,480xx,MI,21477,193292

In [5]:
data.isna().sum()

customer_id             0
emp_title              46
emp_length              0
home_ownership          0
annual_inc              0
annual_inc_joint        0
verification_status     0
zip_code                0
addr_state              0
avg_cur_bal             0
Tot_cur_bal             0
dtype: int64

In [6]:
data.isnull()

,customer_id,emp_title,emp_length,home_ownership,annual_inc,annual_inc_joint,verification_status,zip_code,addr_state,avg_cur_bal,Tot_cur_bal
0,False,True,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
388,False,False,False,False,False,False,False,False,False,False,False
389,False,False,False,False,False,False,False,False,False,False,False
390,False,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,False
392,False,True,False,False,False,False,False,False,False,False,False

In [7]:
data.describe()

         annual_inc   avg_cur_bal   Tot_cur_bal
count  3.930000e+02    393.000000  3.930000e+02
mean   9.754471e+04   8149.829517  8.287220e+04
std    4.678699e+05  12546.264487  1.271750e+05
min    9.000000e+03     31.000000  1.250000e+02
25%    4.500000e+04   1847.000000  1.557700e+04
50%    6.400000e+04   3326.000000  3.021300e+04
75%    8.500000e+04   6927.000000  8.432200e+04
max    9.300086e+06  93203.000000  1.015979e+06

In [8]:
data.drop_duplicates()

,customer_id,emp_title,emp_length,home_ownership,annual_inc,annual_inc_joint,verification_status,zip_code,addr_state,avg_cur_bal,Tot_cur_bal
0,customer 1,NaN,none,Rent,25000.000,none,Verified,010xx,MA,6864,34322
1,customer 2,NaN,none,Mortgage,185000.000,none,Not Verified,010xx,MA,7930,150674
2,customer 3,NaN,none,Mortgage,120000.000,none,Source Verified,015xx,MA,15652,281735
3,customer 4,NaN,none,Mortgage,75000.000,120000,Verified,077xx,NJ,14042,379132
4,customer 5,NaN,none,Mortgage,36000.000,none,Source Verified,480xx,MI,21477,193292
...,...,...,...,...,...,...,...,...,...,...,...
388,customer 389,Trackworker,5 years,Own,67173.508,none,Not Verified,113xx,NY,12990,246805
389,customer 390,General Manager,5 years,Mortgage,70080.000,none,Verified,113xx,NY,27049,189346
390,customer 391,Pharmacy Manager,5 years,Mortgage,125000.000,none,Not Verified,113xx,NY,9580,383200
391,customer 392,Field Supervisor,5 years,Rent,39000.000,none,Source Verified,113xx,NY,2088,22971
392,customer 393,NaN,none,Rent,12900.000,none,Verified,481xx,MI,1275,6375

In [9]:
data.fillna(0)

,customer_id,emp_title,emp_length,home_ownership,annual_inc,annual_inc_joint,verification_status,zip_code,addr_state,avg_cur_bal,Tot_cur_bal
0,customer 1,0,none,Rent,25000.000,none,Verified,010xx,MA,6864,34322
1,customer 2,0,none,Mortgage,185000.000,none,Not Verified,010xx,MA,7930,150674
2,customer 3,0,none,Mortgage,120000.000,none,Source Verified,015xx,MA,15652,281735
3,customer 4,0,none,Mortgage,75000.000,120000,Verified,077xx,NJ,14042,379132
4,customer 5,0,none,Mortgage,36000.000,none,Source Verified,480xx,MI,21477,193292
...,...,...,...,...,...,...,...,...,...,...,...
388,customer 389,Trackworker,5 years,Own,67173.508,none,Not Verified,113xx,NY,12990,246805
389,customer 390,General Manager,5 years,Mortgage,70080.000,none,Verified,113xx,NY,27049,189346
390,customer 391,Pharmacy Manager,5 years,Mortgage,125000.000,none,Not Verified,113xx,NY,9580,383200
391,customer 392,Field Supervisor,5 years,Rent,39000.000,none,Source Verified,113xx,NY,2088,22971
392,customer 393,0,none,Rent,12900.000,none,Verified,481xx,MI,1275,6375

In [10]:
data.fillna('none')

,customer_id,emp_title,emp_length,home_ownership,annual_inc,annual_inc_joint,verification_status,zip_code,addr_state,avg_cur_bal,Tot_cur_bal
0,customer 1,none,none,Rent,25000.000,none,Verified,010xx,MA,6864,34322
1,customer 2,none,none,Mortgage,185000.000,none,Not Verified,010xx,MA,7930,150674
2,customer 3,none,none,Mortgage,120000.000,none,Source Verified,015xx,MA,15652,281735
3,customer 4,none,none,Mortgage,75000.000,120000,Verified,077xx,NJ,14042,379132
4,customer 5,none,none,Mortgage,36000.000,none,Source Verified,480xx,MI,21477,193292
...,...,...,...,...,...,...,...,...,...,...,...
388,customer 389,Trackworker,5 years,Own,67173.508,none,Not Verified,113xx,NY,12990,246805
389,customer 390,General Manager,5 years,Mortgage,70080.000,none,Verified,113xx,NY,27049,189346
390,customer 391,Pharmacy Manager,5 years,Mortgage,125000.000,none,Not Verified,113xx,NY,9580,383200
391,customer 392,Field Supervisor,5 years,Rent,39000.000,none,Source Verified,113xx,NY,2088,22971
392,customer 393,none,none,Rent,12900.000,none,Verified,481xx,MI,1275,6375

In [13]:
data['annual_inc'].max()

9300086.0

In [14]:
data['annual_inc'].nlargest(2).iloc[-1]

np.float64(495000.0)